### ISSUE TITLE
Neo Gui not working

### ISSUE THREAD

**Issue by Jackson094** [neo-project/neo-gui#111]
Every time i open GUI it begins syncing but after about 30 seconds stops and gives following error message.

System.NullReferenceException
Object reference not set to an instance of an object.
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Any Help will be appreciated, Thanks!

**Comment by fabwa** [comment]
Please try to delete the Chain folder and restart the application.
