### ISSUE TITLE
AntShareCore-CLI 1.6.1.0 crash

### ISSUE THREAD

**Issue by marryton007** [neo-project/neo-gui#15]
OnChangeViewReceived: height=3253 view=0 index=3 nv=1
[16:48:57] OnChangeViewReceived: height=3253 view=0 index=2 nv=1
[16:48:57] initialize: height=3253 view=1 index=0 role=Primary
[16:48:57] timeout: height=3253 view=1 state=Primary
[16:48:57] send perpare request: height=3253 view=1
[16:49:00] OnPerpareResponseReceived: height=3253 view=1 index=2
[16:49:00] OnPerpareResponseReceived: height=3253 view=1 index=3
[16:49:00] relay block: f37c7c686306d59feda0bdfdaa281b934f7a7f4adaa1e4b7cf85a8e4e3d94f8b
[16:49:01] persist block: f37c7c686306d59feda0bdfdaa281b934f7a7f4adaa1e4b7cf85a8e4e3d94f8b
[16:49:01] initialize: height=3254 view=0 index=0 role=Backup

Unhandled Exception: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: Coin.TxId, Coin.Index'.
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSa

ant>version
1.6.1.0
ant>

以上是崩溃Log，私链环境

**Comment by sombraSoft** [comment]
@marryton007 What are the steps to repro it?
