### ISSUE TITLE
Unable to create new wallet or convert old wallet

### ISSUE THREAD

**Issue by katzky** [neo-project/neo-gui#184]
Some missing dependencies [Replicon.Cryptography.SCrypt.MMA.dll] in current release gives the following exception when trying to create a new wallet or convert an existing wallet to the new format.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Replicon.Cryptography.SCrypt.MMA.dll' or one of its dependencies. The specified module could not be found.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.<EnsureCrtInitialized>b__3()
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.<>c__DisplayClass8`1.<EscapeExecutionContext>b__5()
   --- End of inner exception stack trace ---
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.EscapeExecutionContext[T](Func`1 callback)
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.EnsureCrtInitialized()
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.DeriveKey(Byte[] password, Byte[] salt, UInt64 N, UInt32 r, UInt32 p, UInt32 derivedKeyLengthBytes)
   at Replicon.Cryptography.SCrypt.SCrypt.DeriveKey(Byte[] password, Byte[] salt, UInt64 N, UInt32 r, UInt32 p, UInt32 derivedKeyLengthBytes)
   at Neo.Cryptography.SCrypt.DeriveKey(Byte[] password, Byte[] salt, Int32 N, Int32 r, Int32 p, Int32 derivedKeyLength)
   at Neo.Wallets.KeyPair.Export(String passphrase, Int32 N, Int32 r, Int32 p)
   at Neo.Implementations.Wallets.NEP6.NEP6Account..ctor(NEP6Wallet wallet, UInt160 scriptHash, KeyPair key, String password)
   at Neo.Implementations.Wallets.NEP6.NEP6Wallet.CreateAccount(Byte[] privateKey)
   at Neo.Wallets.Wallet.CreateAccount()
   at Neo.UI.MainForm.创建钱包数据库NToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

----------------------------------------
Replicon.Cryptography.SCrypt
    Assembly Version: 1.1.6.13
    Win32 Version: 1.1.6.13
    CodeBase: file:///C:/xxx/neo-gui-windows%20(1)/NEO-GUI/Replicon.Cryptography.SCrypt.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jrsikors** [comment]
sounds like problem described in #118 

The first 3 lines are identical:
**_System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Replicon.Cryptography.SCrypt.MMA.dll' or one of its dependencies. The specified module could not be found._**

**Comment by katzky** [comment]
Oh my bad.... I was only looking at open issues.

**Comment by jrsikors** [comment]
Yeah I didn't mean it that way sorry ... github isn't easy to search through old issues.  I actually don't like how this works.  I would rather see 'known issues' stay open for this reason :smile: 

I just remember seeing it a few weeks ago.

I'm assuming it worked then?

**Comment by jrsikors** [comment]
Basically I re-read my post and realized that might have come across as slightly mean like "dude we already talked about this problem"... not intentional and didn't mean it that way at all !
