### ISSUE TITLE
When running neo-gui for the first time. Error file generates with System.TypeInitializationException error.

### ISSUE THREAD

**Issue by ebloshkin** [neo-project/neo-gui#24]
Full Error:

```
System.TypeInitializationException
The type initializer for 'Neo.Core.Blockchain' threw an exception.
   at Neo.Core.Blockchain..ctor()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() in C:\Users\erik\Documents\Visual Studio 2017\Projects\neo-gui\neo-gui\Program.cs:line 109
```

**Comment by erikzhang** [comment]
Can you show me the content of error.log?

**Comment by ebloshkin** [comment]
All the content in error.log:

```
System.TypeInitializationException
The type initializer for 'Neo.Core.Blockchain' threw an exception.
   at Neo.Core.Blockchain..ctor()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() in C:\Users\erik\Documents\Visual Studio 2017\Projects\neo-gui\neo-gui\Program.cs:line 121
```

**Comment by danielcrenna** [comment]
@ebloshkin This is likely caused by a missing `libleveldb.dll` file in your solution working folder, which you need to build yourself and add to the working folder.
