### ISSUE TITLE
Compiling GUI in VS2017 Community Edition

### ISSUE THREAD

**Issue by aboimpinto** [neo-project/neo-gui#42]
I'm trying to compile the UI and I'm getting this error message:
![image](https://user-images.githubusercontent.com/1231687/29469147-57d6a07c-8447-11e7-9c07-1a336c5f1442.png)

I compile the leveldb project with the dll option
![image](https://user-images.githubusercontent.com/1231687/29469189-781a426c-8447-11e7-87f6-649632baafe3.png)

and I copy the dll file to the bin/Debug folder
![image](https://user-images.githubusercontent.com/1231687/29469212-9236c828-8447-11e7-972a-1519021df136.png)

Am I missing anything? Is there any other step missing?
Maybe the "interop" version of the leveldb is not the same? How can I update it?

Paulo Aboim Pinto.

**Comment by erikzhang** [comment]
Click "View Details" link, and check the inner exceptions.

**Comment by aboimpinto** [comment]
this is the information
![image](https://user-images.githubusercontent.com/1231687/29490025-8a83195e-852f-11e7-8127-36213f50529e.png)

and the stackstrace is
![image](https://user-images.githubusercontent.com/1231687/29490028-9e071660-852f-11e7-9f7f-8fb19ce66aa8.png)

**Comment by erikzhang** [comment]
Try to put the libleveldb.dll into x86 or x64 directory.

**Comment by aboimpinto** [comment]
I did that and got the same error.

this is a not document "feature" ;)
after this, the documentation will be better.

**Comment by aboimpinto** [comment]
any other idea about this problem?

**Comment by erikzhang** [comment]
I will release a new version which can log more details about the error.

**Comment by aboimpinto** [comment]
The error.log file was generated with the content:
System.BadImageFormatException
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Neo.Implementations.Blockchains.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() in D:\myDevelop\neo-gui-master\neo-gui\Program.cs:line 108
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by aboimpinto** [comment]
The other post was with a project with the Chain folder copy to the Debug. I did this to make usage of the existem blockchain that I already have.

I did a new clone of the Neo-Gui and this is the content in the error.log file
System.BadImageFormatException
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Neo.Implementations.Blockchains.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main() in d:\myDevelop\GitHubRepos\neo-gui\neo-gui\Program.cs:line 108

**Comment by aboimpinto** [comment]
after many ... many atempts I found the issue
the problem is the leveldb dll is compiled in 32bits and the wallet project is AnyCPU. As soon that I change this configuration to x32, I could run the wallet from code.

**Comment by danielcrenna** [comment]
This could be fixed by adding x86/x64 DLLs in embedded resources, then detecting processor architecture at runtime and choosing the correct one, similar to how SQLite/CLRZMQ packages work, but @erikzhang likely has a reason it's not distributed.

**Comment by aboimpinto** [comment]
agree .. or at least this way should be documented how to make the project compilable!
