### ISSUE TITLE
Please Assist - Neo-gui error and NEO Coins not transferred

### ISSUE THREAD

**Issue by EdwinBoonSing** [neo-project/neo-gui#80]
Dear support
Appreciate if you could assist. I encountered this issue when i login to neo-gui.

![neo-gui has stopped working](https://user-images.githubusercontent.com/32482155/31121137-9aabddea-a869-11e7-86de-5a19a64f0fcc.png)

I did a transfer of NEO from Bittrex yesterday (already passed 24 hours) but it still has NOT shown in my account. The sync is already matched at 1428155/1428155

Thanks
Edwin

**Comment by erikzhang** [comment]
Please upload the contents of error.log

**Comment by Kennith10810** [comment]
I had similar issue..

Running Windows 10,Log Name:      

Application
Source:        Application Error
Date:          10/9/2017 10:13:13 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A

Description:
Faulting application name: neo-gui.exe, version: 2.3.6458.21374, time stamp: 0x59af70fd
Faulting module name: ntdll.dll, version: 10.0.14393.1532, time stamp: 0x5965abad
Exception code: 0xc0000374
Fault offset: 0x00000000000f8363
Faulting process id: 0x27e8
Faulting application start time: 0x01d340d60528fc09
Faulting application path: C:\Users\Kennith\Downloads\neo-gui-windows\Neo\neo-gui.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: c8eb8e26-2771-43ee-bf2b-76e51124da9b
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-09T08:13:13.872868700Z" />
    <EventRecordID>34851</EventRecordID>
    <Channel>Application</Channel>
    <Computer>LAPTOP-4N4AL1R8</Computer>
    <Security />
  </System>
  <EventData>
    <Data>neo-gui.exe</Data>
    <Data>2.3.6458.21374</Data>
    <Data>59af70fd</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.14393.1532</Data>
    <Data>5965abad</Data>
    <Data>c0000374</Data>
    <Data>00000000000f8363</Data>
    <Data>27e8</Data>
    <Data>01d340d60528fc09</Data>
    <Data>C:\Users\Kennith\Downloads\neo-gui-windows\Neo\neo-gui.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>c8eb8e26-2771-43ee-bf2b-76e51124da9b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Please advise how to rectify

**Comment by erikzhang** [comment]
There is a error.log file in the NEO-GUI directory. Please upload it so that we can find the issue.

**Comment by Kennith10810** [comment]
No such file exists in the neo-gui directory?

![neo-gui directory](https://user-images.githubusercontent.com/32634099/31333968-6bf35dde-acec-11e7-934b-1fee2d105129.png)

**Comment by pauboa** [comment]
Hi! This is my first post :) I have the same issue and I would like someone to help me with it. I think the error he is experiencing is the one below:

Microsoft.EntityFrameworkCore.DbUpdateException
An error occurred while updating the entries. See the inner exception for details.
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Neo.Implementations.Wallets.EntityFramework.UserWallet.OnProcessNewBlock(Block block, IEnumerable`1 added, IEnumerable`1 changed, IEnumerable`1 deleted)
   at Neo.Wallets.Wallet.ProcessNewBlock(Block block)
   at Neo.Wallets.Wallet.ProcessBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Microsoft.Data.Sqlite.SqliteException
SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)


Hope that helps :) Thank you very much!!

**Comment by pauboa** [comment]
Hi again!

I solved the issue downloading Neon Wallet (https://neo.org/download) and then once opened the first screen --> "login using a private key". I've just put my private key from Neo-Gui wallet and my NEO was there and also the GAS unclaimed.

Hope this information is useful for other members! Have a nice weekend!
