### ISSUE TITLE
Neo GUI has stopped working, windows 10

### ISSUE THREAD

**Issue by scoriiu** [neo-project/neo-gui#83]
While syncing neo-gui keeps on crashing after several minutes on windows 10. The error.log:

```
System.Collections.Generic.KeyNotFoundException
The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Neo-gui version: 2.3.6474.32109

**Comment by kevmarsden2** [comment]
I'm also having this problem...

**Comment by paintbox** [comment]
My Neo-Gui has stopped working altogether, not sure what to do?

**Comment by kevmarsden2** [comment]
I upgraded my neo-gui to the latest version and it started working correctly. Give it a go if you haven't already...
