### ISSUE TITLE
Neo Gui Redpulse Wallet crashing after opening . Please help

### ISSUE THREAD

**Issue by HelpmeGenuis** [neo-project/neo-gui#89]
System.Collections.Generic.KeyNotFoundException
The given key was not present in the dictionary.
   at Neo.IO.Caching.DataCache`2.GetAndChange(TKey key, Func`1 factory)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by fabwa** [comment]
Your leveldb is most likely corrupted. Try to delete the Chain folder and see whether that fixes the problem. Consider using a bootstrap file from awesome-neo to speed up the new sync
